# Generated by Django 4.1.1 on 2022-09-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HmanagerBackend', '0003_alter_blogcomment_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client_name',
            field=models.CharField(default='name', max_length=300),
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_of_adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_of_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='HmanagerBackend.roomtype'),
        ),
    ]
